spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:gym_workload_db}
    representation:
      uuid: standard

app:
  kafka:
    topics:
      workload-events: trainer.workload.events
      workload-events-dlq: trainer.workload.events.dlq

logging:
  level:
    root: info
    org.springframework.security: debug