spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:gym_workload_db-test}
    representation:
      uuid: standard
  kafka:
    listener:
      auto-startup: false

app:
  kafka:
    topics:
      workload-events: trainer.workload.events.test
      workload-events-dlq: trainer.workload.events.dlq.test

logging:
  level:
    root: info
    org.springframework.security: info